# fly.toml app configuration file generated for good-dog on 2026-08-15T23:31:15-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'good-dog'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATA_DIR = '/data'
  PORT = '8080'
  RUN_RAILS = 'full'

[[mounts]]
  source = 'gooddog_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.http_options]
    [http_service.http_options.response]
      pristine = true

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
